var selfColor = "#beade9"
var friendColor = "#dddddd"
var sidebarColor = "#4d4667"
var sidebarHighlight = "#3e639f"
var sidebarText = "#dddddd"
var button = "#736490"
var buttonDown = "#826ba6"
var buttonText = sidebarText
var spacer = "#dddddd"
var onlineStatus = "#39ce41"
var awayStatus = "#eced44"
var busyStatus = "#d93736"
var offlineStatus = "grey"

var background = "#ffffff"
